
<?php foreach ( $this->main as $main ) :?>

<div  id="article<?php echo $main['id'];  ?>" class="box1">	 
	<div class="fleft">
		<h5>
			<a itemprop='url'  href="<?php echo $this->url(array('articleId' =>  $main['url']),'articles'); ?>"><span itemprop='name' ><?php echo $main['title']; ?></span></a>
			&nbsp; <g:plusone href="<?php  echo $this->url(array('articleId' =>  $main['url']),'articles'); ?>"></g:plusone>
		</h5>
		<p itemprop='articleBody' ><? echo stripcslashes($main['text']);?></p>
	</div>
	<div class="fright">
<?	
if (! empty ( $main ['tags'] )) {	
		$tags = explode ( ',', $main ['tags'] );
		$tags_urls = explode ( ',', $main ['tag_urls'] );
		$i = 0;
		
		foreach ( $tags as $tag ) {					
			echo "<a class=\"link\"  href=\"" . $this->url ( array ('tag' => $tags_urls [$i] ), 'tag' ) . "\" >" .$tag."</a>";
			$i ++;
		
		}
	}
	?> 
		<a href="<?php echo $this->url(array('articleId' =>  $main['url']),'articles'); ?>" class="link">Read More (<?php echo $main['comments']; ?>)</a>
		<a href='https://profiles.google.com/109504873360376523788' itemprop='author' rel='author' title='author profile'>Alex Lukyanov</a>
		<? if (Zend_Auth::getInstance()->hasIdentity() and  Zend_Auth::getInstance()->getIdentity()->isadmin == 1){?>
		  <a href='' class="link" onclick="deletearticle(<?php echo $main['id'];?>); return false;">Delete</a>
		  <a class="link" href='<?php echo   $this->url(array('articleId' =>  $main['url']),'article_edit'); ?>'>Edit</a>
  		<? }?>											
     </div>

	<center>
		<div id="load<?php echo $main['id'];?>" style="display: none;">
			<img alt="loading" src="/public/images/loading.gif"   />
		</div>
	</center>
	<center>
		<div id="goto<?php echo $main['id'];?>" style="display: none; margin: 5px; border: 1px solid #4D9C32; background: #bae4ab;">
			<div class="text">
				<center>Article are deleted.</center>
			</div>
		</div>
	</center>
</div>


<?php endforeach; ?>
<?php


echo $this->paginationControl ( $this->main,
                                    'Sliding',
                                    'pager.phtml'); ?>
 
