<div class="top_news_block">
	<?php foreach ($this->main as $article ):
	$article['text']=stripcslashes($article['text']);	
	
	if (strlen($article['text'])> 126) {		
	$content =substr(preg_replace("/<img[^>]+\>/i", "",$article['text']),3,126);
	$content=substr($content, 0,strrpos($content, ' '))."..";
	} else {
		$content =preg_replace("/<img[^>]+\>/i", "",$article['text']);
	}		
	$content=str_replace('class="padbot"', '', $content);
	?>
	<div class="grid_3">
		<h5><?php echo $article['title'];?></h5>
		 <p class="padbot"> 
		<?php echo $content; ?>
		</p> 
		<a href="<?php echo $this->url(array('articleId' =>  $article['url']),'articles'); ?>" class="button">Read More</a>
	</div>
	<?php endforeach;?>
	<div class="clear"></div>
</div>