<div class="col-sm-6 text-left">
    <div class="text">
        &copy; 2006-<?php echo date("Y") ?> Alex Lukyanov	       
    </div>
</div>
<div class="col-sm-6 text-right">
    <ul class="social-media-icons clearfix">
        <li><a title="Facebok" target="_blank" href="https://www.facebook.com/sashas777"><i class="fa fa-facebook"></i></a></li>
        <li><a title="Twitter" target="_blank" href="https://twitter.com/sashas777"><i class="fa fa-twitter"></i></a></li>
        <li><a title="Google+" target="_blank" href="https://plus.google.com/+AlexLukyanov/"><i class="fa fa-google-plus"></i></a></li> 
        <li><a title="GitHub" target="_blank" href="https://github.com/sashas777"><i class="fa fa-github"></i></a></li>
        <li><a title="Instagram" target="_blank" href="https://instagram.com/sashas777"><i class="fa fa-instagram"></i></a></li>
        <li><a title="LinkedIn" target="_blank" href="https://www.linkedin.com/in/sashas777"><i class="fa fa-linkedin"></i></a></li>
        <li><a title="VK" target="_blank" href="https://vk.com/sashas"><i class="fa fa-vk"></i></a></li>
    </ul>
</div>
            
<script type="text/javascript">
  window.___gcfg = {lang: 'en-US'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

