<div class="col-sm-6 text-left">
    <div class="text">
        &copy; 2006-<?php echo date("Y") ?> Alex Lukyanov	       
    </div>
</div>
<div class="col-sm-6 text-right">
    <ul class="social-media-icons clearfix">
        <li><a title="Facebok" target="_blank" href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a title="Twitter" target="_blank" href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a title="Google+" target="_blank" href="#"><i class="fa fa-google-plus"></i></a></li> 
        <li><a title="GitHub" target="_blank" href="#"><i class="fa fa-github"></i></a></li>
        <li><a title="Instagram" target="_blank" href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a title="LinkedIn" target="_blank" href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a title="VK" target="_blank" href="#"><i class="fa fa-vk"></i></a></li>
    </ul>
</div>
            
 
