<div class=" container_12">
	<div class="wrapper">
		<div class="grid_3 lh24">
			<h4>Copyright</h4>
			Sashas &copy; 2004-2012<br>Zend Framework 1.11
		</div>
		<div class="grid_3 lh20">
			<h4>Contacts</h4>
			Alex Lukyanov<br> E-mail: <a href="mailto: cybergomel@gmail.com">cybergomel@gmail.com</a><br>
		</div>
		<div class="grid_2 suffix_1">
			<h4>Technologies</h4>
			<ul class="list-footer">
				<li><a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a></li>
				<li><a href="http://validator.w3.org/check?uri=referer">XHTML</a></li>
			</ul>
		</div>
		<div class="grid_3">
			<h4>&nbsp;</h4>
			<!-- HotLog -->
			<script type="text/javascript" language="javascript">
<!--
hotlog_js="1.0";
hotlog_r=""+Math.random()+"&amp;s=628345&amp;im=116&amp;r="+escape(
document.referrer)+"&amp;pg="+
escape(window.location.href);
document.cookie="hotlog=1; path=/"; hotlog_r+="&amp;c="+(document.cookie
?"Y":"N");
//-->
</script>
			<script type="text/javascript" language="javascript1.1">
<!--
hotlog_js="1.1";hotlog_r+="&amp;j="+(navigator.javaEnabled()?"Y":"N");
//-->
</script>
			<script type="text/javascript" language="javascript1.2">
<!--
hotlog_js="1.2";
hotlog_r+="&amp;wh="+screen.width+'x'+screen.height+"&amp;px="+
(((navigator.appName.substring(0,3)=="Mic"))?
screen.colorDepth:screen.pixelDepth);
//-->
</script>
			<script type="text/javascript" language="javascript1.3">
<!--
hotlog_js="1.3";
//-->
</script>
			<script type="text/javascript" language="javascript">
<!--
hotlog_r+="&amp;js="+hotlog_js;
document.write("<a href='http://click.hotlog.ru/?628345' target='_top'>");
document.write("<img alt='sashas' src='http://hit30.hotlog.ru/cgi-bin/hotlog/count?"+
hotlog_r+"&amp;' border='0' width='88' height='31' alt='HotLog'/></a>");
//-->
</script>

			<noscript>
				<div style="border: 0 0 0 0px;">
					<a href="http://click.hotlog.ru/?628345" target="_top"> <img
						alt="sashas"
						src="http://hit30.hotlog.ru/cgi-bin/hotlog/count?s=628345&amp;im=116"
						border="0" width="88" height="31" alt="HotLog" /></a>
				</div>
			</noscript>
			<!-- /HotLog -->

		</div>
	</div>
</div>
