<!-- NOT USED -->
<!-- translator-->
<h6>Launguage</h6>	

<p><div align="center" id="google_translate_element"></div></p>

<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', multilanguagePage: true, gaTrack: true, gaId: 'UA-15906461-1'}, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
 				
<h6>Tags</h6>
<p class="main-tags"><?php echo $this->action('tagleft', 'tag'); ?></p>
 

  
      

