

<div class="pagination_bottom">

<ul class="pro_pages">
 

<?php 
$route_params=array();
$route_params['tag']=routes;
$this->route=route;
@$page=page;
if (!empty($page)) {
$this->current_page=$page;
}
if ($this->previous):

$route_params['page']=$this->previous;
	?>
	
		<li><a class="pro_btn pro_prev" href="<?php echo $this->url($route_params, $this->route) ; ?>"><span></span></a></li>
	<?php else: ?>
		<li><a class="pro_btn pro_prev" href="#"><span></span></a></li>
	<?php endif;
	 ?>
	 
	<?php 
	 if ($this->pageCount < 13): /*  Previous  1 2 3 4 5 6 7 8 9 10 11 12  Next  */ ?>

		<?php  for ($i = 1; $i <= $this->pageCount; $i++): ?>
			<?php if ($i == $this->current_page): ?>
			<li class="current"><a href="#" class="pro_btn pro_page"><?php echo $i ?></a></li>			 
			<?php else:
			$route_params['page']=$i;

			?>
			<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page"><?php echo $i ?></a></li>	
			<?php endif ?>
		<?php endfor ?>
<?php elseif ($this->current_page < 9): /*  Previous  1 2 3 4 5 6 7 8 9 10 ... 25 26  Next */ ?>

		<?php for ($i = 1; $i <= 10; $i++): ?>
			<?php if ($i == $this->current_page): ?>
				<li class="current"><a href="#" class="pro_btn pro_page"><?php echo $i ?></a></li>	
			<?php else:
			$route_params['page']=$i;
			?>				 
				<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page"><?php echo $i ?></a></li>	
			<?php endif ?>
		<?php endfor ?>
		<li ><a href="#" class="pro_btn pro_page">&hellip;</a></li>	
		<?php $route_params['page']=$this->pageCount - 1; ?>	
		<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page"><?php echo $this->pageCount - 1 ?></a></li>	
		<?php $route_params['page']=$this->pageCount; ?>
		<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page"><?php echo $this->pageCount ?></a></li>	

<?php elseif ($this->current_page > $this->pageCount - 8): /* Previous  1 2 .. 17 18 19 20 21 22 23 24 25 26  Next  */ ?>
        <?php $route_params['page']=1; ?>
        <li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page">1</a></li>	               
		<?php $route_params['page']=2; ?>
		<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page">2</a></li>			
		<li ><a href="#" class="pro_btn pro_page">&hellip;</a></li>	
	 
		<?php for ($i = $this->pageCount - 9; $i <= $this->pageCount; $i++): ?>
			<?php if ($i == $this->current_page): ?>
				<li class="current"><a href="#" class="pro_btn pro_page"><?php echo $i ?></a></li>	
			<?php else: ?>
			<?php $route_params['page']=$i; ?>
				<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page"><?php echo $i ?></a></li>
			<?php endif ?>
		<?php endfor ?>
 
<?php else: /* » Previous  1 2 ... 5 6 7 8 9 10 11 12 13 14 ...25 26  Next */ ?>
         <?php $route_params['page']=1; ?>
		<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page">1</a></li>	
		<?php $route_params['page']=2; ?>
		<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page">2</a></li>
		<li ><a href="#" class="pro_btn pro_page">&hellip;</a></li>	

		<?php for ($i = $this->current_page - 5; $i <= $this->current_page + 5; $i++): ?>
			<?php if ($i == $this->current_page): ?>
				<li class="current"><a href="#" class="pro_btn pro_page"><?php echo $i ?></a></li>	
			<?php else: ?>
			<?php $route_params['page']=$i; ?>
				<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page"><?php echo $i ?></a></li>
			<?php endif ?>
		<?php endfor ?>

		<li ><a href="#" class="pro_btn pro_page">&hellip;</a></li>	
		<?php $route_params['page']=$this->pageCount - 1; ?>
		<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page"><?php echo $this->pageCount - 1 ?></a></li>	
		<?php $route_params['page']=$this->pageCount; ?>
		<li ><a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_page"><?php echo $this->pageCount ?></a></li>

	<?php endif ?>


	<?php if ($this->next): ?>
	<?php $route_params['page']=$this->next; ?>		
		<li> <a href="<?php echo $this->url($route_params, $this->route); ?>" class="pro_btn pro_next"><span></span></a></li>
	<?php else: ?>
		<li> <a href="#" class="pro_btn pro_next"><span></span></a></li>
	<?php endif ?>

 </ul>
</div>
