<?php 
	$route_params=array();
	$route_params['tag']=routes;
	$this->route=route;
	@$page=page;
	if (!empty($page)) {
		$this->current_page=$page;
	}
	$previous=0;
	if ($this->previous){
		$route_params['page']=$this->previous;
		$previous=1;
	}
	$next=0;
	if ($this->next){
		$route_params['page']=$this->next;
		$next=1;
	}
?>
<div class="pagination-container isolated-block col-xs-12 col-lg-12 text-center clearfix">
	<ul class="pagination-list">		 
		<li <?php if (!$previous): ?>class="disabled"<?php endif; ?>><a href="<?php if ($previous): echo $this->url($route_params, $this->route) ; else: echo "javascript:void(0);";  endif;  ?>">«</a></li>		
		<?php if ($this->pageCount < 13): /*  Previous  1 2 3 4 5 6 7 8 9 10 11 12  Next  */ ?>
			<?php  for ($i = 1; $i <= $this->pageCount; $i++): ?>
				<?php if ($i == $this->current_page): ?>
					<li class="active"><a href="<?php echo $this->url($route_params, $this->route); ?>"><?php echo $i ?></a></li>			 
				<?php else:
					$route_params['page']=$i; ?>
					<li><a href="<?php echo $this->url($route_params, $this->route); ?>"><?php echo $i ?></a></li>	
				<?php endif ?>
			<?php endfor ?>	
		<?php elseif ($this->current_page < 9): /*  Previous  1 2 3 4 5 6 7 8 9 10 ... 25 26  Next */ ?>
			<?php for ($i = 1; $i <= 10; $i++): ?>
				<?php if ($i == $this->current_page): ?>
					<li class="active"><a href="<?php echo $this->url($route_params, $this->route); ?>"><?php echo $i ?></a></li>	
				<?php else:
					$route_params['page']=$i;?>				 
					<li ><a href="<?php echo $this->url($route_params, $this->route); ?>"><?php echo $i ?></a></li>	
				<?php endif ?>
			<?php endfor ?>		
			<li><a href="javascript:void(0);">&hellip;</a></li>	
			<?php $route_params['page']=$this->pageCount - 1; ?>	
			<li><a href="<?php echo $this->url($route_params, $this->route); ?>"><?php echo $this->pageCount - 1 ?></a></li>	
			<?php $route_params['page']=$this->pageCount; ?>
			<li><a href="<?php echo $this->url($route_params, $this->route); ?>"><?php echo $this->pageCount ?></a></li>	
		<?php elseif ($this->current_page > $this->pageCount - 8): /* Previous  1 2 .. 17 18 19 20 21 22 23 24 25 26  Next  */ ?>
	        <?php $route_params['page']=1; ?>
	        <li><a href="<?php echo $this->url($route_params, $this->route); ?>">1</a></li>	               
			<?php $route_params['page']=2; ?>
			<li><a href="<?php echo $this->url($route_params, $this->route); ?>">2</a></li>			
			<li><a href="javascript:void(0);">&hellip;</a></li>			 
			<?php for ($i = $this->pageCount - 9; $i <= $this->pageCount; $i++): ?>				 
				<?php $route_params['page']=$i; ?>
				<li <?php if ($i == $this->current_page): ?> class="active" <?php endif ?>><a href="<?php echo $this->url($route_params, $this->route); ?>"><?php echo $i ?></a></li>		 
			<?php endfor ?>
			<?php else: /* << 1 2 ... 5 6 7 8 9 10 11 12 13 14 ...25 26  Next */ ?>
			         <?php $route_params['page']=1; ?>
					<li><a href="<?php echo $this->url($route_params, $this->route); ?>">1</a></li>	
					<?php $route_params['page']=2; ?>
					<li><a href="<?php echo $this->url($route_params, $this->route); ?>">2</a></li>
					<li><a href="javascript:void(0);" >&hellip;</a></li>			
					<?php for ($i = $this->current_page - 5; $i <= $this->current_page + 5; $i++): ?>
						<?php $route_params['page']=$i; ?>						 
						<li <?php if ($i == $this->current_page): ?> class="active" <?php endif ?>><a href="<?php echo $this->url($route_params, $this->route); ?>"><?php echo $i ?></a></li>						 
					<?php endfor; ?>			
					<li><a href="javascript:void(0);">&hellip;</a></li>	
					<?php $route_params['page']=$this->pageCount - 1; ?>
					<li><a href="<?php echo $this->url($route_params, $this->route); ?>"><?php echo $this->pageCount - 1 ?></a></li>	
					<?php $route_params['page']=$this->pageCount; ?>
					<li><a href="<?php echo $this->url($route_params, $this->route); ?>"><?php echo $this->pageCount ?></a></li>
		<?php endif ?>			 		
		<li <?php if (!$next): ?>class="disabled"<?php endif; ?>><a href="<?php if ($next): echo $this->url($route_params, $this->route); else: echo "javascript:void(0);"; endif;?>">»</a></li>
	</ul>
</div>