<div class="slideshow-content-container clearfix">
    <div class="row">
        <div class="col-xs-12">
			<div class="slideshow owl-carousel" >
			    <div><img alt="Sashas.org" class="img-responsive img-thumbnail slider" src="<?php echo $this->baseUrl(); ?>/public/media/slideshow/slide1.jpg" /></div>
			    <div><img alt="Sashas.org" class="img-responsive img-thumbnail slider" src="<?php echo $this->baseUrl(); ?>/public/media/slideshow/slide2.jpg" /></div>
			    <div><img alt="Sashas.org" class="img-responsive img-thumbnail slider" src="<?php echo $this->baseUrl(); ?>/public/media/slideshow/slide3.jpg" /></div>
			    <div><img alt="Sashas.org" class="img-responsive img-thumbnail slider" src="<?php echo $this->baseUrl(); ?>/public/media/slideshow/slide4.jpg" /></div>
			</div>
        </div>
    </div>
    <script type="text/javascript" >
        $(document).ready(function(){
			$(".owl-carousel").owlCarousel({
			    'items':1,
			    singleItem: true,
			    autoPlay: true,
			     loop:true,
			});
        });        
    </script>
</div>   
