
<div id="gallery">
	<!-- slider -->
	<div class="gallery">
		<ul class="items">
			<li><img src="/public/design/images/slide1.jpg" alt="" />
				<div class="banner">
<!-- 					<div class="b-title">See what we can do for your business!</div> -->
<!-- 					<div class="b-button"> -->
<!-- 						<a href="more.html">sign up now</a> -->
<!-- 					</div> -->
				</div></li>
			<li><img src="/public/design/images/slide2.jpg" alt="" />
				<div class="banner">				
				</div></li>
			<li><img src="/public/design/images/slide3.jpg" alt="" />
				<div class="banner">					
				</div></li>
			<li><img src="/public/design/images/slide4.jpg" alt="" />
				<div class="banner">					
				</div></li>
		</ul>
	</div>
	<!-- slider end -->
	<div class="pag">
		<div class="img-pags">
			<ul>
				<li><a href="#"><span><img
							src="/public/design/images/small-slide1.jpg" alt="" /></span></a></li>
				<li><a href="#"><span><img
							src="/public/design/images/small-slide2.jpg" alt="" /></span></a></li>
				<li><a href="#"><span><img
							src="/public/design/images/small-slide3.jpg" alt="" /></span></a></li>
				<li><a href="#"><span><img
							src="/public/design/images/small-slide4.jpg" alt="" /></span></a></li>
			</ul>
		</div>
	</div>
</div>