<div   class="post-item isolated-block col-xs-12 col-lg-12">
	<h1>Login</h1>
	<div class="post-content text-content col-md-offset-4 clearfix">
		<form id="login-form"  role="form" enctype="application/x-www-form-urlencoded" class="login-form  form-horizontal" action="" method="post"> 
			
		 <div class="form-group">
		 	<label for="email" class="required col-sm-2  control-label">Email:</label>
		 	<div class="col-sm-3">
		 		<input class="form-control" type="text" name="email" id="email" value=""  placeholder="Email" maxlength="80">
		 	</div>
		 </div>
		 
		 <div class="form-group">
		 	<label for="password" class="required col-sm-2  control-label">Password:</label>
		 	<div class="col-sm-3">
			 	<input class="form-control" type="password" name="password" id="password" placeholder="Password" value="" maxlength="30">
		 	</div>
		 </div>
		 
		 <div class="form-group">
		    <div class="col-sm-offset-2 col-sm-10">
				<button class="btn btn-default" name="submit" id="login_submit" type="button" >Login</button>
			</div>
		</div>
		</form>
	</div>
	<div id="load" class="col-lg-12 ajax-loader hide clearfix"><img  class="center-block" alt="loading.." src="<?php echo $this->baseUrl(); ?>/public/images/ajaxLoader.gif" border="0" /></div>
	<div id="goto" class="col-lg-12 ajax-loader-success text-center hide clearfix"><span class="center-block">You are logged in.</span></div>					
</div>
 
