
<div id="enter" class="box1">
<form id="form" enctype="application/x-www-form-urlencoded" class="enter" action="" method="post"> 

<div class="login-title" ><label for="email" class="required">Email:</label></div>

<input class="pro_btn pro_print2" type="text" name="email" id="email" value="" maxlength="80"></dd>
<div class="login-title"><label for="password" class="required">Password:</label></div>

<input class="pro_btn pro_print2" type="password" name="password" id="password" value="" maxlength="30"></dd>
<div class="login-button">
<button class="pro_btn pro_print2" name="submit" id="submit" type="button" onclick="login()">Login</button>
</div>
</form>
</div>

<center><span id="load" style="display: none;"><img alt="loading..." src="/public/images/loading.gif" border="0"></span></center>
<div id="goto" style="display: none;margin:5px;border:1px solid #4D9C32;background:#bae4ab;"><center>Welcome ;)</center></div>
