<meta name="viewport"
	content="width=device-width, initial-scale=1.0, user-scalable=no">
<meta charset="UTF-8">

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">

    function initialize() { 
    var latlng = new google.maps.LatLng(40.780541,-99.060059);
    var myOptions = {
      zoom: 4,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.TERRAIN
    };   
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    
    <?php echo $this->maps; ?>
  }	    
    google.maps.event.addDomListener(window, 'load', initialize);
    </script>

	<div class="box1" id="map_canvas" style="width: 620px; height: 660px"></div>


