<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script type="text/javascript">
    function initialize() { 
    var latlng = new google.maps.LatLng(36.083973,-72.642166);
    var myOptions = {
      zoom: 4,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.TERRAIN
    };   
    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    <?php echo $this->maps; ?>
  }	    
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div class="row"> 	    
	<div class="col-xs-12 post-item col-lg-12">
		<div class="box1" id="map_canvas"  class="span12" style="height: 660px; max-height: 660px;"></div>
	</div>	
</div>

