<?php echo $this->doctype() ?>
<html  xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>     
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="yandex-verification" content="6f4ab80be6c9bdef" />
<meta name="google-site-verification" content="R8aPGqBwGsGVZwuxjN2TWT054HQSRVAB8xTM9mY2jYc" />
<meta name="y_key" content="24d7d9ed1731b2b7" />
<meta name="google-translate-customization" content="3406a9f953e799e2-80af7884513ab628-gdbcdfc05ef0c8891-b" />
<meta name="robots" content="all" />
<meta itemprop="creator" content="Alex Lukyanov" />
<meta itemprop="name" content="Sashas.org" />
<meta itemprop="description" content="Blog of Alex Lukyanov">
<?php echo $this->headTitle() ?>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta itemprop="image" content="<?php echo $this->baseUrl(); ?>/public/media/homepage/small-slide1.jpg" />
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<?php  echo $this->headMeta()->appendName('copyright', '&copy; 2006-2014 Alex Lukyanov'); ?>
<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/public/images/favicon.ico" type="image/x-icon" /> 
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/bootstrap-theme.min.css" type="text/css" />     
<link href="<?php echo $this->baseUrl(); ?>/public/css/style.css" media="screen" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/owl.carousel.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/owl.theme.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/lightbox.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/public/css/sashas.css" media="screen"  type="text/css" />
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"  />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
<script type="text/javascript" src="http://userapi.com/js/api/openapi.js?34"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/menu.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/responsive_images.js"></script>
<script ype="text/javascript"  src="<?php echo $this->baseUrl(); ?>/public/js//lightbox.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/js/sashas.js"></script>
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-15906461-1', 'auto');
  ga('send', 'pageview');

</script>
</head>
<?php  $homepage=(isset($this->homepage) ? 1 : 0 ); ?>
<body class="light-theme <?php if (!$homepage) { ?>subpage-body<?php } ?>">
	<!-- Google Tag Manager -->
	<noscript><iframe class="hide" src="//www.googletagmanager.com/ns.html?id=GTM-ML92RZ"
	></iframe></noscript>
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-ML92RZ');</script>
	<!-- End Google Tag Manager -->
 
    <div class="body main-container outer-container clearfix">
        <div class="container">
        	<header class="header isolated-block clearfix">
                <div class="logo">
                        <a href="<?php echo $this->url(array(), 'default', true) ?>"><img id="logo" alt="Alex Lukyanov" src="<?php echo $this->baseUrl(); ?>/public/images/logo.png" /></a>
                </div>                 
                <div class="clearfix" id="main-menu-container">                	 
                    <div class="btn btn-outline-inverse visible-xs" id="mobile-menu-icon"><span class="glyphicon glyphicon-th"></span></div>
                    <?php echo $this->partial('top_menu.phtml'); ?>           
                </div>                  
            </header>
            <?php if ($homepage)  echo $this->partial('slider.phtml'); ?>	
 			<div class="row"> 		 
	            <div class="col-xs-12 col-lg-12"  itemscope itemtype="http://schema.org/Blog">
	            	<?php echo $this->layout()->messages; ?>
	            	 <?php /* echo $this->partial('menu.phtml'); @todo left menu  */ ?>
	            	 	<?php echo $this->layout()->content; ?>
	            </div>
	        </div>
	        
            <div class="footer row clearfix">
            <?php echo $this->partial('footer.phtml'); ?>
            </div>	                             
        </div>
    </div>        	
</body>
</html>
 